### ISSUE TITLE
Publish latest code to dockerhub

### ISSUE THREAD

**Issue by jsmartt** [appleboy/drone-packer#12]
I see that the master branch has been updated to packer 1.6.6 a few weeks ago, and that is awesome (we need it to publish to Azure Shared Image Gallery), but it doesn't look like it's been published to Docker Hub yet, so I have to build my own image to use it. Would you mind publishing the latest version of the code to docker hub?
Thanks!

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Try `linux-amd64` flag: https://hub.docker.com/layers/appleboy/drone-packer/linux-amd64/images/sha256-6d8dd1b41207d4e6d2f037cba819008c48e0c87dacd1a3375a8c8f13b19982d1?context=explore

**Comment by jsmartt** [comment]
Thanks!
