### ISSUE TITLE
Unable to build qemu images

### ISSUE THREAD

**Issue by rustycl0ck** [appleboy/drone-packer#7]
I am trying to build `ubuntu` from this repo - https://github.com/jakobadam/packer-qemu-templates, which is all `qemu` based but it errors out complaining that the `qemu` binary couldn't be found. [failure here](https://cloud.drone.io/rustycl0ck/packer-qemu-templates/2/1/2)

![Screenshot from 2019-10-10 09-49-11](https://user-images.githubusercontent.com/1299606/66530617-02b95480-eaf8-11e9-816e-6dc00d6c361d.png)

**Comment by appleboy** [comment]
try GitHub Actions. See https://github.com/appleboy/drone-packer/blob/master/.github/workflows/docker.yml
